// apps/desktop/src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { listen } from "@tauri-apps/api/event";
  import { Activity, AlertCircle, ChevronDown, Circle, Copy, Download, FolderUp, ListTree, LogOut, Pause, Play, Search, ShieldCheck, Smartphone, Square, TerminalSquare, Wifi, X } from "lucide-svelte";
  import * as api from "./api";
  import type { AndroidApp, AndroidDevice, HttpTransaction, LogIncident, ProxyStatus } from "./types";

  type Screen = "traffic" | "logs";
  type Tab = "Overview" | "Request" | "Response" | "Compare" | "cURL" | "Timeline";
  type InspectorEvent<T> = { kind: string; payload: T };
  let screen: Screen = "traffic";
  let tab: Tab = "Overview";
  let proxy: ProxyStatus = "stopped";
  let devices: AndroidDevice[] = [];
  let device = "";
  let apps: AndroidApp[] = [];
  let packageName = "";
  let packageSearch = "";
  let packagePickerOpen = false;
  let devicesOpen = false;
  let transactions: HttpTransaction[] = [];
  let selectedId = "";
  let incidents: LogIncident[] = [];
  let query = "";
  let changedOnly = false;
  let errorsOnly = false;
  let capturing = false;
  let paused = false;
  let busy = false;
  let notice = "";
  let desktopHost = "Resolving…";
  let activeSessionId: string | undefined;
  let transactionRefreshInFlight = false;
  let expandedIssue = "";
  let importInput: HTMLInputElement;

  const duration = (tx: HttpTransaction) => tx.timing.response_complete_ms == null ? undefined : tx.timing.response_complete_ms - tx.timing.request_started_ms;
  const state = (tx: HttpTransaction) => !tx.response ? "Pending" : tx.response.status >= 400 ? "Failed" : tx.comparison?.differences.some(d => !d.ignored) ? "Changed" : "Captured";
  const body = (value: HttpTransaction["request"]["body"] | undefined) => {
    if (!value || value.storage === "empty") return "No body";
    if (value.storage === "unavailable") return value.reason;
    return new TextDecoder().decode(new Uint8Array(value.storage === "inline" ? value.bytes : value.preview));
  };
  const pretty = (value: string) => { try { return JSON.stringify(JSON.parse(value), null, 2); } catch { return value; } };
  const statusLabel = () => capturing ? "Capturing live" : proxy === "running" ? "Proxy ready" : "Ready to capture";
  const captured = () => transactions.filter(tx => tx.request.method.toUpperCase() !== "CONNECT");
  const selected = () => captured().find(tx => tx.id === selectedId) ?? visible()[0];
  const visible = () => captured().filter(tx => {
    const searchable = `${tx.request.method} ${tx.request.host} ${tx.request.path} ${tx.response?.status ?? ""}`.toLowerCase();
    return searchable.includes(query.toLowerCase()) && (!changedOnly || state(tx) === "Changed") && (!errorsOnly || state(tx) === "Failed" || tx.correlated_incidents.length > 0);
  });
  const selectedDevice = () => devices.find(item => item.serial === device);
  const matchingApps = () => {
    const search = packageSearch.trim().toLowerCase();
    return apps
      .filter(app => !search || `${app.package_name} ${app.version_name ?? ""}`.toLowerCase().includes(search))
      .slice(0, search ? 50 : 8);
  };
  const copy = (value: string) => { void navigator.clipboard.writeText(value); notice = "Copied to clipboard"; };
  const closePickers = () => { packagePickerOpen = false; devicesOpen = false; packageSearch = ""; };
  const endpointId = (tx: HttpTransaction) => tx.endpoint_identity && `${tx.endpoint_identity.method} ${tx.endpoint_identity.host} ${tx.endpoint_identity.path_template}`;
  async function approveBaseline(tx: HttpTransaction) {
    const id = endpointId(tx);
    if (!id) { notice = "This response does not have a comparable endpoint identity yet."; return; }
    try { await api.approveBaseline(id, tx.id); notice = "Response saved as the JSON-key baseline for this endpoint."; }
    catch (error) { notice = `Could not save baseline: ${String(error)}`; }
  }
  function upsertIncident(issue: LogIncident) {
    const existing = incidents.find(item => item.signature === issue.signature);
    const occurrence_count = Math.max(issue.occurrence_count, existing ? existing.occurrence_count + 1 : 1);
    incidents = [{ ...issue, occurrence_count }, ...incidents.filter(item => item.signature !== issue.signature)].slice(0, 100);
  }
  const upsertTransaction = (transaction: HttpTransaction) => {
    if (transaction.session_id !== activeSessionId) return;
    transactions = [transaction, ...transactions.filter(item => item.id !== transaction.id)];
  };
  async function refreshTransactions() {
    if (transactionRefreshInFlight) return;
    transactionRefreshInFlight = true;
    try { transactions = await api.listTransactions(); }
    catch { /* Live events remain the primary update path. */ }
    finally { transactionRefreshInFlight = false; }
  }
  async function refreshProxyStatus() {
    try {
      const next = await api.getProxyStatus();
      if (capturing && proxy === "running" && next !== "running") {
        capturing = false;
        paused = false;
        notice = "Capture proxy stopped unexpectedly. Reopen the companion to start a fresh capture.";
      }
      proxy = next;
    } catch { /* Keep the last known state while the native bridge reconnects. */ }
  }

  async function refreshDevices() {
    try {
      devices = await api.discoverDevices();
      const nextDevice = devices.some(item => item.serial === device && item.authorization_status === "authorized")
        ? device
        : devices.find(item => item.connection_type === "usb" && item.authorization_status === "authorized")?.serial
          ?? devices.find(item => item.authorization_status === "authorized")?.serial
          ?? "";
      if (nextDevice !== device) {
        device = nextDevice;
        // A USB device is normally selected automatically, so load its
        // debuggable apps here rather than waiting for a second click.
        void loadApps();
        void resolveHost();
      }
    } catch (error) { notice = `Could not refresh Android devices: ${String(error)}`; }
  }
  async function loadApps() {
    if (!device) { apps = []; packageName = ""; return; }
    try {
      apps = await api.listInstalledApps(device);
      // Package discovery can briefly return an incomplete list while ADB is
      // reconnecting. Never clear the target from a live capture because the
      // capture session remains scoped to that package.
      if (packageName && !capturing && !apps.some(item => item.package_name === packageName)) packageName = "";
    } catch (error) { notice = `Could not load debuggable packages: ${String(error)}`; }
  }
  function chooseDevice(serial: string) { device = serial; closePickers(); void loadApps(); void resolveHost(); }
  function choosePackage(name: string) { packageName = name; packageSearch = ""; packagePickerOpen = false; notice = `Selected ${name}`; }
  async function resolveHost() {
    try { desktopHost = await api.getProxyHost(selectedDevice()?.connection_type ?? "usb"); } catch { desktopHost = "Unavailable"; }
  }
  async function start() {
    if (selectedDevice()?.connection_type === "usb") { await connectCompanion(); return; }
    if (!packageName) { notice = "Choose a package before starting capture."; packagePickerOpen = true; return; }
    busy = true;
    try {
      const current = selectedDevice();
      if (!current) throw new Error("Choose an authorized Android device first.");
      if (current.connection_type !== "emulator") {
        await connectCompanion();
        return;
      }
      activeSessionId = await api.startProxy();
      const host = await api.getProxyHost(current.connection_type);
      desktopHost = host;
      if (current.connection_type === "emulator") {
        const config = await api.getProxyConfiguration();
        await api.configureAndroidProxy(device, host, config.port);
      }
      await api.startLogcatCapture(device, packageName).catch(() => undefined);
      transactions = []; incidents = []; selectedId = ""; capturing = true; paused = false;
      notice = `Capture active for ${packageName}. Navigate the app to see traffic.`;
    } catch (error) { await api.stopProxy().catch(() => undefined); notice = String(error); }
    finally { busy = false; }
  }
  async function stop() {
    busy = true;
    try {
      if (device && selectedDevice()?.connection_type === "emulator") await api.clearAndroidProxy(device);
      await api.stopProxy(); capturing = false; paused = false; notice = "Capture stopped.";
    } catch (error) { notice = `Could not stop capture: ${String(error)}`; }
    finally { busy = false; }
  }
  async function connectCompanion() {
    busy = true;
    try {
      const current = selectedDevice();
      if (!current) throw new Error("Choose an authorized Android device first.");
      if (current.connection_type !== "usb") throw new Error("Companion capture requires a USB-connected Android device.");
      if (!packageName) throw new Error("Choose the target package before opening the companion.");
      const connection = await api.openUsbCompanion(device, packageName);
      activeSessionId = connection.session_id;
      capturing = true;
      transactions = [];
      await refreshTransactions();
      await api.startLogcatCapture(device, packageName).catch(() => undefined);
      notice = `Desktop capture endpoint is ready on port ${connection.port}. On your phone, stop and reconnect VPN once to apply this endpoint.`;
    } catch (error) { notice = `Could not open companion: ${String(error)}`; }
    finally { busy = false; }
  }
  async function exportCapture() { try { notice = `Exported capture to ${await api.exportCaptureToFile()}`; } catch (error) { notice = String(error); } }
  async function importCapture(event: Event) {
    const file = (event.target as HTMLInputElement).files?.[0];
    if (!file) return;
    try { await api.importCapture(await file.text()); transactions = await api.listTransactions(); notice = "Imported redacted capture."; } catch (error) { notice = String(error); }
    (event.target as HTMLInputElement).value = "";
  }
  onMount(() => {
    void refreshProxyStatus();
    void refreshDevices();
    // Discovery is now a single lightweight ADB command, so poll promptly and
    // surface a newly attached USB device without a noticeable delay.
    const deviceTimer = window.setInterval(refreshDevices, 750);
    // The native event bridge can miss a status change after a window restore.
    // Reconcile it so the controls never claim that a stopped proxy is live.
    const proxyTimer = window.setInterval(() => void refreshProxyStatus(), 1000);
    // Tauri events can be missed while the WebView is suspended or restored.
    // Reconcile the current capture session frequently so new requests appear
    // without requiring a view change.
    const transactionTimer = window.setInterval(() => void refreshTransactions(), 500);
    const unlisteners = [
      listen<InspectorEvent<ProxyStatus>>("proxy-status-changed", event => proxy = event.payload.payload),
      listen<InspectorEvent<HttpTransaction>>("transaction-created", event => upsertTransaction(event.payload.payload)),
      listen<InspectorEvent<HttpTransaction>>("transaction-updated", event => upsertTransaction(event.payload.payload)),
      listen<InspectorEvent<HttpTransaction>>("transaction-completed", event => upsertTransaction(event.payload.payload)),
      listen<InspectorEvent<LogIncident>>("incident-created", event => upsertIncident(event.payload.payload))
    ];
    return () => { window.clearInterval(deviceTimer); window.clearInterval(proxyTimer); window.clearInterval(transactionTimer); void Promise.all(unlisteners).then(items => items.forEach(stop => stop())); };
  });
</script>

<svelte:window onclick={closePickers} />
<main class="svelte-app">
  <aside class="sidenav">
    <div class="wordmark"><Activity size={22}/><span><small>Android diagnostics</small></span></div>
    <nav aria-label="Primary navigation">
      <button class:active={screen === "traffic"} onclick={() => screen = "traffic"}><ListTree/><span><b>Traffic lab</b><small>Requests & schema changes</small></span></button>
      <button class:active={screen === "logs"} onclick={() => screen = "logs"}><TerminalSquare/><span><b>Log inspector</b><small>Errors & warnings</small></span>{#if incidents.length}<i>{incidents.length}</i>{/if}</button>
    </nav>
    <div class:live={capturing} class="capture-status"><Circle size={10}/><span><b>{capturing ? "Capture active" : "Ready"}</b><small>{packageName || "Select a package"}</small></span></div>
  </aside>

  <section class:logs-mode={screen === "logs"} class="svelte-main">
    <header class="topbar">
      <div class:running={proxy === "running"} class="connection-pill"><span class="pulse"></span>{statusLabel()}</div>
      <div class="picker">
        <button class="select-trigger" onclick={(event) => { event.stopPropagation(); devicesOpen = !devicesOpen; packagePickerOpen = false; }}><Smartphone/>{selectedDevice()?.model || device || "Select device"}<ChevronDown/></button>
        {#if devicesOpen}<div class="menu device-menu">{#each devices as item}<button class:selected={device === item.serial} onclick={() => chooseDevice(item.serial)}><span><b>{item.model || item.serial}</b><small>{item.connection_type} · {item.authorization_status}</small></span></button>{/each}{#if !devices.length}<span class="menu-empty">No Android devices found</span>{/if}</div>{/if}
      </div>
      <div class="picker package-picker">
        <button class="select-trigger package-trigger" disabled={busy || !device} onclick={(event) => { event.stopPropagation(); packagePickerOpen = !packagePickerOpen; devicesOpen = false; packageSearch = ""; }}><span class="app-dot"></span><span>{packageName || "Select package"}</span><ChevronDown/></button>
        {#if packagePickerOpen}<div class="menu package-menu"><label class="package-filter"><Search size={16}/><input aria-label="Search Android packages" bind:value={packageSearch} placeholder="Search package name" onclick={(event) => event.stopPropagation()} /></label>{#each matchingApps() as app}<button class:selected={packageName === app.package_name} onclick={() => choosePackage(app.package_name)}><span><b>{app.package_name}</b><small>{app.version_name ? `${app.version_name} · ` : ""}{app.debuggable ? "Debug build" : "Installed package"}</small></span>{#if packageName === app.package_name}<ShieldCheck size={15}/>{/if}</button>{/each}{#if packageSearch && !matchingApps().length}<button class="use-package" onclick={() => choosePackage(packageSearch)}><span><b>Use “{packageSearch}”</b><small>Enter this package directly</small></span></button>{:else if !packageSearch && apps.length > 8}<span class="menu-empty">Search {apps.length} packages.</span>{/if}</div>{/if}
      </div>
      {#if capturing}<button class="quiet" onclick={() => void connectCompanion()} disabled={busy}><Wifi/>{busy ? "Opening companion…" : "Open companion"}</button><button class="quiet" onclick={() => paused = !paused}>{#if paused}<Play/>{:else}<Pause/>{/if}{paused ? "Resume" : "Pause"}</button><button class="stop" onclick={() => void stop()} disabled={busy}><Square/>Stop</button>{:else}<button class="primary" onclick={() => void start()} disabled={busy}><Play/>{busy ? "Preparing…" : selectedDevice()?.connection_type === "usb" ? "Open companion" : "Start capture"}</button>{/if}
    </header>

    {#if notice}<div class="notice-bar"><AlertCircle size={16}/><span>{notice}</span><button aria-label="Dismiss notice" onclick={() => notice = ""}><X size={15}/></button></div>{/if}
    {#if screen === "traffic"}
      <section class="hero"><div><span>Traffic lab</span><h1>See what your app is really doing.</h1><p>Capture scoped traffic from <b>{packageName || "your selected package"}</b>.</p></div><div class="hero-host"><small>DESKTOP HOST</small><b>{desktopHost}</b></div></section>
      <section class="toolbar">
        <label class="search-field"><Search size={17}/><input bind:value={query} placeholder="Search requests, hosts, paths…" /></label>
        <button class:active={changedOnly} onclick={() => changedOnly = !changedOnly}>Changed <b>{captured().filter(tx => state(tx) === "Changed").length}</b></button>
        <button class:active={errorsOnly} onclick={() => errorsOnly = !errorsOnly}>Errors <b>{captured().filter(tx => state(tx) === "Failed").length}</b></button>
        <div class="toolbar-spacer"></div><button class="icon-button" title="Export redacted capture" onclick={() => void exportCapture()}><Download/></button><input class="hidden" bind:this={importInput} type="file" accept="application/json,.json" onchange={importCapture}/><button class="icon-button" title="Import capture" onclick={() => importInput?.click()}><FolderUp/></button>
      </section>
      <section class="workbench">
        <div class="request-list"><div class="list-heading"><span>LIVE REQUESTS</span><small>{visible().length} visible</small></div><div class="request-scroll">{#each visible() as tx (tx.id)}<button class:selected={selected()?.id === tx.id} class:failed={state(tx) === "Failed"} class:changed={state(tx) === "Changed"} class="request-row" onclick={() => { selectedId = tx.id; tab = "Overview"; }}><time>{new Date(tx.created_at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" })}</time><b class="method">{tx.request.method}</b><span class="request-target"><b>{tx.request.host}</b><small>{tx.request.path}</small></span><span>{tx.response?.status ?? "…"}</span><span class="request-state">{state(tx)}</span></button>{/each}{#if !visible().length}<div class="empty-state"><Activity size={28}/><b>No traffic yet</b><span>{capturing ? "Use the selected app and requests will stream in here." : "Start a capture when you are ready."}</span></div>{/if}</div></div>
        <aside class="inspector">{#if selected()} {@const tx = selected()!}<div class="inspector-heading"><div><span>{tx.request.method}</span><b>{tx.request.host}{tx.request.path}</b></div><button class="icon-button" onclick={() => copy(`${tx.request.scheme}://${tx.request.host}${tx.request.path}`)}><Copy/></button></div><nav class="tabs">{#each ["Overview", "Request", "Response", "Compare", "cURL", "Timeline"] as name}<button class:active={tab === name} onclick={() => tab = name as Tab}>{name}</button>{/each}</nav><div class="detail-panel">{#if tab === "Overview"}<div class="overview-grid"><label>Status<b>{tx.response?.status ?? "Pending"}</b></label><label>Duration<b>{duration(tx) ?? "—"} ms</b></label><label>Content type<b>{tx.response?.content_type || tx.request.content_type || "Unknown"}</b></label><label>Capture quality<b>{tx.capture_quality}</b></label></div>{:else if tab === "Request" || tab === "Response"}{@const message = tab === "Request" ? tx.request : tx.response}<h3>{tab} headers</h3><div class="header-list">{#each message?.headers || [] as header}<div><b>{header.name}</b><span>{header.value}</span></div>{/each}</div><h3>Body</h3><pre>{pretty(body(message?.body))}</pre>{:else if tab === "Compare"}<div class="compare-summary"><div><span>JSON shape comparison</span><b>{tx.comparison ? tx.comparison.compatibility.replaceAll("_", " ") : "Waiting for a comparable response"}</b><small>Scalar values are ignored; only JSON keys, nesting, array item shapes, and types are compared.</small></div><button class="quiet" onclick={() => void approveBaseline(tx)}>Set baseline</button></div>{#if tx.comparison?.differences.length}<div class="difference-list">{#each tx.comparison.differences as difference}<article class:critical={difference.severity === "critical"} class:ignored={difference.ignored}><div><b>{difference.kind.replaceAll("_", " ")}</b><code>{difference.path || "Response"}</code></div><p>{difference.explanation}</p>{#if difference.previous || difference.current}<small><span>Before: {difference.previous || "—"}</span><span>After: {difference.current || "—"}</span></small>{/if}</article>{/each}</div>{:else}<div class="compare-empty"><ShieldCheck/><b>{tx.comparison ? "No JSON-key changes" : "No comparison yet"}</b><span>{tx.comparison ? "This response matches the observed JSON shape." : "Set a baseline or wait for another response to this endpoint."}</span></div>{/if}{:else if tab === "cURL"}<pre>{tx.curl?.multiline || "cURL will be generated once the request is complete."}</pre>{:else}<ol class="timeline"><li>Request started <time>{new Date(tx.timing.request_started_ms).toLocaleTimeString()}</time></li>{#if tx.timing.request_complete_ms}<li>Request sent</li>{/if}{#if tx.timing.response_started_ms}<li>Response headers received</li>{/if}{#if tx.timing.response_complete_ms}<li>Response complete</li>{/if}</ol>{/if}</div>{:else}<div class="empty-state inspector-empty"><ListTree size={30}/><b>Select a request</b><span>Its headers, body and timing will appear here.</span></div>{/if}</aside>
      </section>
    {:else}
      <section class="hero logs-hero"><div><span>Log inspector</span><h1>Every actionable error, in context.</h1><p>Live diagnostic evidence for <b>{packageName || "your selected package"}</b>.</p></div>{#if !capturing}<button class="primary" onclick={() => void start()}><Play/>Start monitoring</button>{/if}</section>
      <section class="log-metrics"><article><small>Detected</small><b>{incidents.length}</b></article><article><small>Errors</small><b class="danger-text">{incidents.filter(item => ["crash", "error", "anr"].includes(item.category)).length}</b></article><article><small>Monitoring</small><b>{capturing ? "Live" : "Paused"}</b></article></section>
      <section class="log-feed">{#each incidents as issue (issue.signature)}{@const expanded = expandedIssue === issue.signature}<article class:expanded class="issue-card"><div class="issue-kind"><AlertCircle size={18}/>{issue.category.replaceAll("_", " ")}</div><div class="issue-body"><button class="issue-toggle" aria-expanded={expanded} onclick={() => expandedIssue = expanded ? "" : issue.signature}><div class="issue-title"><div><h2>{issue.title}</h2><p>{issue.summary}</p></div><div class="issue-meta">{#if issue.occurrence_count > 1}<b class="occurrences">×{issue.occurrence_count}</b>{/if}<time>{new Date(issue.occurred_at).toLocaleTimeString()}</time><ChevronDown class="issue-chevron"/></div></div><div class="issue-context">{issue.where_occurred || issue.foreground_activity || "App context unavailable"}</div></button>{#if expanded}<div class="issue-details"><div class="issue-details-inner"><div class="issue-summary"><div><small>Summary</small><p>{issue.summary}</p></div><div><small>Root cause</small><p>{issue.root_cause || issue.likely_cause || "Still being classified from the captured evidence."}</p></div><div><small>How it happened</small><p>{issue.how_occurred || issue.likely_cause || "No additional execution context was recorded."}</p></div></div><div class="issue-evidence"><div><small>Reproduction / context</small><ol>{#each issue.reproduction_steps as step}<li>{step}</li>{/each}</ol></div><div><small>Captured logs</small><pre>{issue.lines.map(line => `${line.timestamp_ms}  ${line.level.padEnd(5)}  ${line.tag}: ${line.message}`).join("\n") || "No raw Logcat lines were retained for this issue."}</pre></div></div><button class="quiet" onclick={() => copy(issue.lines.map(line => `${line.level} ${line.tag}: ${line.message}`).join("\n"))}><Copy/>Copy logs</button></div></div>{/if}</div></article>{/each}{#if !incidents.length}<div class="empty-state log-empty"><ShieldCheck size={32}/><b>No issues detected</b><span>{capturing ? "App Tester is watching Logcat for actionable problems." : "Start monitoring to see errors and warnings here."}</span></div>{/if}</section>
    {/if}
  </section>
</main>

// apps/desktop/src/App.tsx
import { useEffect, useMemo, useState } from "react";
import { listen } from "@tauri-apps/api/event";
import { Activity, Cable, Circle, Copy, KeyRound, Pause, Play, QrCode, Search, Settings, ShieldCheck, Square, TestTube2, Trash2, Wifi, X } from "lucide-react";
import * as api from "./api";
import type { AndroidApp, AndroidCertificateInstall, AndroidDevice, BodyStorage, HttpTransaction, LogIncident, ProxyStatus, QrPairingChallenge } from "./types";

type InspectorTab = "Overview" | "Request" | "Response" | "Compare" | "cURL" | "Logs" | "Timeline";
export const duration = (tx: HttpTransaction) => tx.timing.response_complete_ms == null ? undefined :
  tx.timing.response_complete_ms - tx.timing.request_started_ms;
export const bodyText = (body?: BodyStorage) => {
  if (!body || body.storage === "empty") return "";
  if (body.storage === "unavailable") return body.reason;
  const bytes = body.storage === "inline" ? body.bytes : body.preview;
  return new TextDecoder().decode(new Uint8Array(bytes));
};
export const displayState = (tx: HttpTransaction) => {
  if (!tx.response) return "Pending";
  if (tx.response.status >= 400) return "Failed";
  if (!tx.comparison?.baseline_transaction_id) return "New";
  if (tx.comparison?.differences.some((difference) => !difference.ignored)) return "Changed";
  return "Unchanged";
};
const jsonView = (value: string) => {
  try { return JSON.stringify(JSON.parse(value), null, 2); } catch { return value; }
};

export function App() {
  const [transactions, setTransactions] = useState<HttpTransaction[]>([]);
  const [selectedId, setSelectedId] = useState<string>();
  const [proxy, setProxy] = useState<ProxyStatus>("stopped");
  const [capturing, setCapturing] = useState(false);
  const [paused, setPaused] = useState(false);
  const [query, setQuery] = useState("");
  const [changedOnly, setChangedOnly] = useState(false);
  const [errorsOnly, setErrorsOnly] = useState(false);
  const [tab, setTab] = useState<InspectorTab>("Overview");
  const [devices, setDevices] = useState<AndroidDevice[]>([]);
  const [device, setDevice] = useState("");
  const [apps, setApps] = useState<AndroidApp[]>([]);
  const [packageName, setPackageName] = useState("");
  const [notice, setNotice] = useState("");
  const [qrPairing, setQrPairing] = useState<QrPairingChallenge>();
  const [qrStatus, setQrStatus] = useState<"waiting"|"paired"|"failed">("waiting");
  const [codePairingOpen, setCodePairingOpen] = useState(false);
  const [usbWifiOpen, setUsbWifiOpen] = useState(false);
  const [pairingHost, setPairingHost] = useState("");
  const [pairingPort, setPairingPort] = useState("");
  const [pairingCode, setPairingCode] = useState("");
  const [connecting, setConnecting] = useState(false);
  const [connectionError, setConnectionError] = useState("");
  const [certificateInstall, setCertificateInstall] = useState<AndroidCertificateInstall>();
  const [incidents, setIncidents] = useState<LogIncident[]>([]);

  useEffect(() => {
    void api.getProxyStatus().then(setProxy);
    void api.discoverDevices().then((items) => { setDevices(items); setDevice(items[0]?.serial ?? ""); });
    const stops = [
      listen<{payload: ProxyStatus}>("proxy-status-changed", e => setProxy(e.payload.payload)),
      listen<{payload: HttpTransaction}>("transaction-created", e =>
        setTransactions(current => [e.payload.payload, ...current])),
      listen<{payload: HttpTransaction}>("transaction-updated", e =>
        setTransactions(current => current.map(tx => tx.id === e.payload.payload.id ? e.payload.payload : tx))),
      listen<{payload: HttpTransaction}>("transaction-completed", e =>
        setTransactions(current => current.some(tx => tx.id === e.payload.payload.id)
          ? current.map(tx => tx.id === e.payload.payload.id ? e.payload.payload : tx)
          : [e.payload.payload, ...current])),
      listen<{payload: LogIncident}>("incident-created", e => {
        const incident = e.payload.payload;
        setIncidents(current => [incident, ...current].slice(0, 100));
        setNotice(`Logcat: ${incident.title} — ${incident.message}`);
      }),
    ];
    return () => { void Promise.all(stops).then(unlisteners => unlisteners.forEach(stop => stop())); };
  }, []);
  useEffect(() => {
    if (!device) return;
    void api.listInstalledApps(device).then(items => { setApps(items); setPackageName(items[0]?.package_name ?? ""); });
  }, [device]);

  const visible = useMemo(() => transactions.filter(tx => {
    const haystack = `${tx.request.method} ${tx.request.host} ${tx.request.path} ${tx.response?.status ?? ""}`.toLowerCase();
    return haystack.includes(query.toLowerCase()) && (!changedOnly || displayState(tx) === "Changed") &&
      (!errorsOnly || displayState(tx) === "Failed" || tx.correlated_incidents.length > 0);
  }), [transactions, query, changedOnly, errorsOnly]);
  const selected = transactions.find(tx => tx.id === selectedId) ?? visible[0];

  async function start() {
    try {
      await api.startProxy();
      if (device) await api.configureAndroidProxy(device, "10.0.2.2", 8080);
      if (device && packageName) await api.startLogcatCapture(device, packageName);
      setCapturing(true); setNotice("Capture active. Navigate the Android app manually.");
    } catch (error) {
      if (String(error).includes("CA certificate")) await setupHttpsCapture();
      else setNotice(String(error));
    }
  }
  async function stop() {
    await api.stopProxy(); setCapturing(false);
    if (device) await api.clearAndroidProxy(device).catch(() => undefined);
  }
  async function pairWithQr() {
    try {
      setQrStatus("waiting");
      const challenge = await api.beginQrPairing();
      setQrPairing(challenge);
      const result = await api.finishQrPairing(challenge.id);
      setQrStatus("paired");
      setNotice(`Wireless device paired at ${result.endpoint}`);
      const items = await api.discoverDevices();
      setDevices(items);
      setDevice(items.find(item => item.connection_type === "wireless")?.serial ?? items[0]?.serial ?? "");
    } catch (error) {
      setQrStatus("failed");
      setNotice(String(error));
    }
  }
  async function refreshWirelessDevices(endpoint: string) {
    setNotice(`Wireless device connected at ${endpoint}`);
    const items = await api.discoverDevices();
    setDevices(items);
    setDevice(items.find(item => item.connection_type === "wireless")?.serial ?? items[0]?.serial ?? "");
  }
  async function submitCodePairing() {
    setConnecting(true); setConnectionError("");
    try {
      const result = await api.pairWithCode(pairingHost.trim(), Number(pairingPort), pairingCode.trim());
      await refreshWirelessDevices(result.endpoint);
      setCodePairingOpen(false);
    } catch (error) { setConnectionError(String(error)); }
    finally { setConnecting(false); }
  }
  async function submitUsbWifi() {
    if (!device) return;
    setConnecting(true); setConnectionError("");
    try {
      const result = await api.enableUsbWifi(device);
      await refreshWirelessDevices(result.endpoint);
      setUsbWifiOpen(false);
    } catch (error) { setConnectionError(String(error)); }
    finally { setConnecting(false); }
  }
  async function setupHttpsCapture() {
    if (!device) { setNotice("Select an authorized Android device before setting up HTTPS capture."); return; }
    setConnecting(true); setConnectionError("");
    try {
      const install = await api.prepareAndroidCertificateInstall(device);
      setCertificateInstall(install);
    } catch (error) { setConnectionError(String(error)); setNotice(String(error)); }
    finally { setConnecting(false); }
  }
  async function deleteAll() {
    if (!window.confirm("Delete all captured API history? This cannot be undone.")) return;
    try { await api.deleteAllTransactions(); setTransactions([]); setSelectedId(undefined); setIncidents([]); setNotice("All captured API history was deleted."); }
    catch (error) { setNotice(String(error)); }
  }
  async function testYesterday() {
    if (!window.confirm("Replay every testable API captured yesterday? Requests may include state-changing methods. Requests containing redacted credentials or data are skipped.")) return;
    setConnecting(true);
    try {
      const summary = await api.testYesterdaysApis();
      setNotice(`Yesterday replay: ${summary.completed} completed, ${summary.changed} changed, ${summary.failed} failed, ${summary.skipped} skipped.`);
    } catch (error) { setNotice(String(error)); }
    finally { setConnecting(false); }
  }
  function copy(value: string) { void navigator.clipboard.writeText(value); setNotice("Copied to clipboard"); }

  return <main className="shell">
    <header>
      <div className="brand"><Activity/><strong>App Tester</strong><span>Android Inspector</span></div>
      <div className={`proxy ${proxy}`}><Circle/>Proxy {proxy.replaceAll("_"," ")}</div>
      <select aria-label="Device" value={device} onChange={e=>setDevice(e.target.value)}>
        <option value="">Select device</option>{devices.map(item=><option key={item.serial}>{item.serial}</option>)}
      </select>
      <button className="qr-trigger" onClick={()=>void pairWithQr()}><QrCode/>Connect via QR</button>
      <button onClick={()=>{setConnectionError(""); setCodePairingOpen(true);}}><KeyRound/>Pair with code</button>
      <button onClick={()=>{setConnectionError(""); setUsbWifiOpen(true);}}><Cable/>USB to Wi-Fi</button>
      <button onClick={()=>void setupHttpsCapture()}><ShieldCheck/>HTTPS setup</button>
      <select aria-label="Package" value={packageName} onChange={e=>setPackageName(e.target.value)}>
        <option value="">Select package</option>{apps.map(app=><option key={app.package_name}>{app.package_name}</option>)}
      </select>
      {capturing ? <button className="danger" onClick={()=>void stop()}><Square/>Stop capture</button> :
        <button className="primary" onClick={()=>void start()}><Play/>Start capture</button>}
      <button title="Settings"><Settings/></button>
    </header>
    <section className="filters">
      <label className="search"><Search/><input placeholder="Search method, host, path, status…" value={query} onChange={e=>setQuery(e.target.value)}/></label>
      <button className={changedOnly?"active":""} onClick={()=>setChangedOnly(v=>!v)}>Changed only</button>
      <button className={errorsOnly?"active":""} onClick={()=>setErrorsOnly(v=>!v)}>Errors only</button>
      <button disabled={connecting} onClick={()=>void testYesterday()}><TestTube2/>Test yesterday’s APIs</button>
      <button className="danger" onClick={()=>void deleteAll()}><Trash2/>Delete all</button>
      <button onClick={()=>setPaused(v=>!v)}>{paused?<Play/>:<Pause/>}{paused?"Resume":"Pause"} UI</button>
      <span className="count">{visible.length} requests</span>
    </section>
    {notice && <div className="notice">{notice}</div>}
    <section className="workspace">
      <div className="traffic">
        <div className="table-head"><span>Time</span><span>Method</span><span>Host / Path</span><span>Status</span><span>Duration</span><span>Size</span><span>Change</span><span>Issues</span></div>
        <div className="rows">
          {visible.map(tx => <button key={tx.id} onClick={()=>setSelectedId(tx.id)}
            className={`row ${selected?.id===tx.id?"selected":""} ${displayState(tx).toLowerCase()}`}>
            <span>{new Date(tx.created_at).toLocaleTimeString([], {hour12:false})}</span>
            <b className={`method ${tx.request.method.toLowerCase()}`}>{tx.request.method}</b>
            <span className="target"><strong>{tx.request.host}</strong><small>{tx.request.path}</small></span>
            <span>{tx.response?.status ?? "—"}</span><span>{duration(tx) == null ? "Pending" : `${duration(tx)} ms`}</span>
            <span>{tx.response ? `${tx.response.decoded_size} B` : "—"}</span>
            <span className="change">{displayState(tx)}</span><span>{tx.correlated_incidents.length || "—"}</span>
          </button>)}
          {!visible.length && <div className="empty"><ShieldCheck/><strong>No captured traffic yet</strong>
            <span>{proxy==="running"?"Navigate the selected Android app manually.":"Start capture and configure the device proxy to see requests live."}</span></div>}
        </div>
      </div>
      <aside className="inspector">
        {selected ? <><div className="inspector-title"><div><b>{selected.request.method}</b><strong>{selected.request.host}{selected.request.path}</strong></div>
          <button onClick={()=>copy(`${selected.request.scheme}://${selected.request.host}${selected.request.path}`)}><Copy/>URL</button></div>
          <nav>{(["Overview","Request","Response","Compare","cURL","Logs","Timeline"] as InspectorTab[]).map(name=>
            <button className={tab===name?"active":""} onClick={()=>setTab(name)} key={name}>{name}</button>)}</nav>
          <div className="panel">{tab==="Overview" && <Overview tx={selected}/>}
            {tab==="Request" && <Message headers={selected.request.headers} body={bodyText(selected.request.body)} onCopy={copy}/>}
            {tab==="Response" && <Message headers={selected.response?.headers ?? []} body={bodyText(selected.response?.body)} onCopy={copy}/>}
            {tab==="Compare" && <Compare tx={selected}/>}
            {tab==="cURL" && <Code value={selected.curl?.multiline ?? "cURL is generated when the request is captured."} onCopy={copy}/>}
            {tab==="Logs" && <Logs incidents={incidents}/>}
            {tab==="Timeline" && <Timeline tx={selected}/>}</div>
        </> : <div className="empty"><Activity/><strong>Select a request</strong><span>Request, response, comparison, cURL and correlated logs will appear here.</span></div>}
      </aside>
    </section>
    {qrPairing && <div className="modal-backdrop" role="presentation">
      <section className="qr-dialog" role="dialog" aria-modal="true" aria-labelledby="qr-title">
        <button className="close" aria-label="Close" onClick={()=>setQrPairing(undefined)}><X/></button>
        <div className="qr-heading"><Wifi/><div><h2 id="qr-title">Connect Android over Wi-Fi</h2>
          <p>Android 11 or newer · same Wi-Fi network</p></div></div>
        {qrStatus==="waiting" ? <><div className="qr-image" dangerouslySetInnerHTML={{__html:qrPairing.qr_svg}}/>
          <ol><li>Open <b>Settings → Developer options → Wireless debugging</b>.</li>
            <li>Tap <b>Pair device with QR code</b>.</li><li>Scan this code with Android’s pairing scanner.</li></ol>
          <div className="pairing-status"><span className="spinner"/>Waiting for the device…</div>
          <small>Expires {new Date(qrPairing.expires_at).toLocaleTimeString()}. This QR grants ADB access; only scan it on a device you control.</small></> :
          qrStatus==="paired" ? <div className="pair-result success"><ShieldCheck/><h3>Device connected</h3><p>The wireless device is now available in the device selector.</p>
            <button className="primary" onClick={()=>setQrPairing(undefined)}>Done</button></div> :
          <div className="pair-result failed"><Circle/><h3>Pairing failed</h3><p>{notice}</p><button onClick={()=>void pairWithQr()}>Generate a new QR</button></div>}
      </section>
    </div>}
    {codePairingOpen && <div className="modal-backdrop" role="presentation">
      <section className="qr-dialog connection-dialog" role="dialog" aria-modal="true" aria-labelledby="code-pair-title">
        <button className="close" aria-label="Close" onClick={()=>setCodePairingOpen(false)}><X/></button>
        <div className="qr-heading"><KeyRound/><div><h2 id="code-pair-title">Pair Android with a code</h2><p>Reliable alternative to Android’s QR scanner</p></div></div>
        <ol><li>On Android, open <b>Developer options → Wireless debugging</b>.</li><li>Tap <b>Pair device with pairing code</b>.</li><li>Enter its IP address, pairing port, and six-digit code below.</li></ol>
        <label>Device IP or host<input value={pairingHost} placeholder="192.168.1.44" onChange={e=>setPairingHost(e.target.value)} autoComplete="off"/></label>
        <label>Pairing port<input inputMode="numeric" value={pairingPort} placeholder="37123" onChange={e=>setPairingPort(e.target.value)}/></label>
        <label>Six-digit pairing code<input inputMode="numeric" value={pairingCode} placeholder="123456" maxLength={6} onChange={e=>setPairingCode(e.target.value.replace(/\D/g, ""))}/></label>
        {connectionError && <p className="connection-error">{connectionError}</p>}
        <button className="primary submit" disabled={connecting || !pairingHost || !pairingPort || pairingCode.length !== 6} onClick={()=>void submitCodePairing()}>{connecting ? "Pairing…" : "Pair device"}</button>
      </section>
    </div>}
    {usbWifiOpen && <div className="modal-backdrop" role="presentation">
      <section className="qr-dialog connection-dialog" role="dialog" aria-modal="true" aria-labelledby="usb-wifi-title">
        <button className="close" aria-label="Close" onClick={()=>setUsbWifiOpen(false)}><X/></button>
        <div className="qr-heading"><Cable/><div><h2 id="usb-wifi-title">Use USB once, then Wi-Fi</h2><p>For an already USB-authorized device</p></div></div>
        <p>This enables legacy ADB over Wi-Fi on <b>{device || "the selected device"}</b> at port 5555, discovers its Wi-Fi IP, and connects it wirelessly.</p>
        <p className="warning">Keep the device and this Mac on the same network. Disconnecting USB after the wireless connection succeeds is safe.</p>
        {connectionError && <p className="connection-error">{connectionError}</p>}
        <button className="primary submit" disabled={connecting || !device} onClick={()=>void submitUsbWifi()}>{connecting ? "Connecting…" : "Enable Wi-Fi connection"}</button>
      </section>
    </div>}
    {certificateInstall && <div className="modal-backdrop" role="presentation">
      <section className="qr-dialog connection-dialog" role="dialog" aria-modal="true" aria-labelledby="certificate-title">
        <button className="close" aria-label="Close" onClick={()=>setCertificateInstall(undefined)}><X/></button>
        <div className="qr-heading"><ShieldCheck/><div><h2 id="certificate-title">Finish HTTPS capture setup</h2><p>One required Android security confirmation</p></div></div>
        <p>App Tester generated the local certificate, copied it to your device, and opened Android’s credential installer.</p>
        <ol><li>Choose <b>CA certificate</b> if Android asks for a credential type.</li><li>Select <b>AppTester-HTTPS-CA.pem</b> from Downloads.</li><li>Confirm the Android warning, then return here.</li></ol>
        <p className="warning">Android requires this approval so no desktop app can silently add a certificate that could inspect encrypted traffic.</p>
        <button className="primary submit" onClick={()=>{setCertificateInstall(undefined); void start();}}>I installed it — start capture</button>
      </section>
    </div>}
  </main>;
}
function Overview({tx}:{tx:HttpTransaction}) { return <div className="overview">
  <label>Status<strong>{tx.response?.status ?? "Pending"}</strong></label><label>Duration<strong>{duration(tx) ?? "—"} ms</strong></label>
  <label>Content type<strong>{tx.response?.content_type ?? tx.request.content_type ?? "Unknown"}</strong></label>
  <label>HTTP<strong>{tx.response?.http_version ?? tx.request.http_version}</strong></label>
  <label>Capture quality<strong>{tx.capture_quality}</strong></label><label>Change<strong className={displayState(tx)==="Changed"?"red":""}>{displayState(tx)}</strong></label>
</div>; }
function Message({headers,body,onCopy}:{headers:{name:string;value:string}[];body:string;onCopy:(v:string)=>void}) {
  return <><h3>Headers <button onClick={()=>onCopy(headers.map(h=>`${h.name}: ${h.value}`).join("\n"))}><Copy/>Copy</button></h3>
    <div className="headers">{headers.map((h,i)=><div key={`${h.name}-${i}`}><b>{h.name}</b><span>{h.value}</span></div>)}</div>
    <h3>Body <button onClick={()=>onCopy(body)}><Copy/>Copy raw</button></h3><pre>{jsonView(body) || "No body"}</pre></>;
}
function Code({value,onCopy}:{value:string;onCopy:(v:string)=>void}) { return <div className="code"><button onClick={()=>onCopy(value)}><Copy/>Copy</button><pre>{value}</pre></div>; }
function Compare({tx}:{tx:HttpTransaction}) { const diffs=tx.comparison?.differences ?? []; return <div>
  <h3>{diffs.length ? `${diffs.length} differences` : "No compatible comparison available"}</h3>
  {diffs.map((diff,i)=><article className={`diff ${diff.severity}`} key={i}><b>{diff.path ?? diff.kind}</b><span>{diff.explanation}</span>
    <pre>Previous: {diff.previous ?? "—"}{"\n"}Current: {diff.current ?? "—"}</pre></article>)}</div>; }
function Logs({incidents}:{incidents:LogIncident[]}) { return incidents.length ? <div className="logs">{incidents.map(incident =>
  <article className="log-incident" key={incident.id}><b>{incident.title}</b><span>{incident.message}</span>
    {incident.lines.map((line, index)=><pre key={index}>{line.level} {line.tag}: {line.message}</pre>)}</article>)}</div> :
  <div className="empty compact">No actionable logcat errors captured for the selected app yet.</div>; }
function Timeline({tx}:{tx:HttpTransaction}) { return <ol className="timeline">
  <li>Request started <time>{new Date(tx.timing.request_started_ms).toLocaleTimeString()}</time></li>
  {tx.timing.request_complete_ms&&<li>Request complete</li>}{tx.timing.response_started_ms&&<li>Response headers</li>}
  {tx.timing.response_complete_ms&&<li>Response complete</li>}</ol>; }
